name: deploy to EKS
on: [push]

env:

  AWS_REGION: eu-central-1
  CLUSTER_NAME: demo1

jobs:
  deploy-to-eks:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS client
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name:  Login to cluster
        run: >
          aws eks update-kubeconfig
          --region ${AWS_REGION}
          --name ${CLUSTER_NAME}

      - name: Test cluster access
        run: kubectl get nodes

      - name: Deploy Demo Helm Chart
        run: helm upgrade my-demo-chart100 helm/ --values helm/values.yaml --install

      - name: Deploy Demo Helm Chart
        run: helm upgrade my-demo-chart200 helm/ --values helm/values200.yaml --install

      - name: Get Deployments
        run: kubectl get deployments

      - name: Get Services
        run: kubectl get services

      - name: Get Pods
        run: kubectl get pods
